/*
 * File:           C:\Users\Leander\Documents\Hardware\Endstufe\SigmaStudio\TestDesign\Output\systemfiles_IC_2.h
 *
 * Created:        Friday, October 11, 2024 9:04:13 PM
 * Description:    TestDesigndspproj:IC 2 program data.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2024 Analog Devices, Inc. All rights reserved.
 */
#ifndef __SYSTEMFILES_IC_2_H__
#define __SYSTEMFILES_IC_2_H__

#include "../SigmaStudioFW.h"
#include "systemfiles_IC_2_REG.h"

#define DEVICE_ARCHITECTURE_IC_2                  "ADAU1966"
#define DEVICE_ADDR_IC_2                          0x04


/* Register Default - IC 2.PLL_CLK_CTRL0 Register.PLL_CLK_CTRL0 */
ADI_REG_TYPE R0_PLL_CLK_CTRL0_IC_2_Default[REG_PLL_CLK_CTRL0_IC_2_BYTE] = {
0x05
};

/* Register Default - IC 2.PLL_CLK_CTRL1 Register.PLL_CLK_CTRL1 */
ADI_REG_TYPE R1_PLL_CLK_CTRL1_IC_2_Default[REG_PLL_CLK_CTRL1_IC_2_BYTE] = {
0x2A
};

/* Register Default - IC 2.PDN_THRMSENS_CTRL_1 Register.PDN_THRMSENS_CTRL_1 */
ADI_REG_TYPE R2_PDN_THRMSENS_CTRL_1_IC_2_Default[REG_PDN_THRMSENS_CTRL_1_IC_2_BYTE] = {
0xA4
};

/* Register Default - IC 2.PDN_CTRL2 Register.PDN_CTRL2 */
ADI_REG_TYPE R3_PDN_CTRL2_IC_2_Default[REG_PDN_CTRL2_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.PDN_CTRL3 Register.PDN_CTRL3 */
ADI_REG_TYPE R4_PDN_CTRL3_IC_2_Default[REG_PDN_CTRL3_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC_CTRL0 Register.DAC_CTRL0 */
ADI_REG_TYPE R5_DAC_CTRL0_IC_2_Default[REG_DAC_CTRL0_IC_2_BYTE] = {
0x14
};

/* Register Default - IC 2.DAC_CTRL1 Register.DAC_CTRL1 */
ADI_REG_TYPE R6_DAC_CTRL1_IC_2_Default[REG_DAC_CTRL1_IC_2_BYTE] = {
0x02
};

/* Register Default - IC 2.DAC_CTRL2 Register.DAC_CTRL2 */
ADI_REG_TYPE R7_DAC_CTRL2_IC_2_Default[REG_DAC_CTRL2_IC_2_BYTE] = {
0x06
};

/* Register Default - IC 2.DAC_MUTE1 Register.DAC_MUTE1 */
ADI_REG_TYPE R8_DAC_MUTE1_IC_2_Default[REG_DAC_MUTE1_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC_MUTE2 Register.DAC_MUTE2 */
ADI_REG_TYPE R9_DAC_MUTE2_IC_2_Default[REG_DAC_MUTE2_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DACMSTR_VOL Register.DACMSTR_VOL */
ADI_REG_TYPE R10_DACMSTR_VOL_IC_2_Default[REG_DACMSTR_VOL_IC_2_BYTE] = {
0x20
};

/* Register Default - IC 2.DAC01_VOL Register.DAC01_VOL */
ADI_REG_TYPE R11_DAC01_VOL_IC_2_Default[REG_DAC01_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC02_VOL Register.DAC02_VOL */
ADI_REG_TYPE R12_DAC02_VOL_IC_2_Default[REG_DAC02_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC03_VOL Register.DAC03_VOL */
ADI_REG_TYPE R13_DAC03_VOL_IC_2_Default[REG_DAC03_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC04_VOL Register.DAC04_VOL */
ADI_REG_TYPE R14_DAC04_VOL_IC_2_Default[REG_DAC04_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC05_VOL Register.DAC05_VOL */
ADI_REG_TYPE R15_DAC05_VOL_IC_2_Default[REG_DAC05_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC06_VOL Register.DAC06_VOL */
ADI_REG_TYPE R16_DAC06_VOL_IC_2_Default[REG_DAC06_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC07_VOL Register.DAC07_VOL */
ADI_REG_TYPE R17_DAC07_VOL_IC_2_Default[REG_DAC07_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC08_VOL Register.DAC08_VOL */
ADI_REG_TYPE R18_DAC08_VOL_IC_2_Default[REG_DAC08_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC09_VOL Register.DAC09_VOL */
ADI_REG_TYPE R19_DAC09_VOL_IC_2_Default[REG_DAC09_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC10_VOL Register.DAC10_VOL */
ADI_REG_TYPE R20_DAC10_VOL_IC_2_Default[REG_DAC10_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC11_VOL Register.DAC11_VOL */
ADI_REG_TYPE R21_DAC11_VOL_IC_2_Default[REG_DAC11_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC12_VOL Register.DAC12_VOL */
ADI_REG_TYPE R22_DAC12_VOL_IC_2_Default[REG_DAC12_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC13_VOL Register.DAC13_VOL */
ADI_REG_TYPE R23_DAC13_VOL_IC_2_Default[REG_DAC13_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC14_VOL Register.DAC14_VOL */
ADI_REG_TYPE R24_DAC14_VOL_IC_2_Default[REG_DAC14_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC15_VOL Register.DAC15_VOL */
ADI_REG_TYPE R25_DAC15_VOL_IC_2_Default[REG_DAC15_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC16_VOL Register.DAC16_VOL */
ADI_REG_TYPE R26_DAC16_VOL_IC_2_Default[REG_DAC16_VOL_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.CM_SEL_PAD_STRGTH Register.CM_SEL_PAD_STRGTH */
ADI_REG_TYPE R27_CM_SEL_PAD_STRGTH_IC_2_Default[REG_CM_SEL_PAD_STRGTH_IC_2_BYTE] = {
0x00
};

/* Register Default - IC 2.DAC_POWER1 Register.DAC_POWER1 */
ADI_REG_TYPE R28_DAC_POWER1_IC_2_Default[REG_DAC_POWER1_IC_2_BYTE] = {
0xAA
};

/* Register Default - IC 2.DAC_POWER2 Register.DAC_POWER2 */
ADI_REG_TYPE R29_DAC_POWER2_IC_2_Default[REG_DAC_POWER2_IC_2_BYTE] = {
0xAA
};

/* Register Default - IC 2.DAC_POWER3 Register.DAC_POWER3 */
ADI_REG_TYPE R30_DAC_POWER3_IC_2_Default[REG_DAC_POWER3_IC_2_BYTE] = {
0xAA
};

/* Register Default - IC 2.DAC_POWER4 Register.DAC_POWER4 */
ADI_REG_TYPE R31_DAC_POWER4_IC_2_Default[REG_DAC_POWER4_IC_2_BYTE] = {
0xAA
};


/*
 * Default Download
 */
#define DEFAULT_DOWNLOAD_SIZE_IC_2 32

void default_download_IC_2() {
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_PLL_CLK_CTRL0_IC_2_ADDR, REG_PLL_CLK_CTRL0_IC_2_BYTE, R0_PLL_CLK_CTRL0_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_PLL_CLK_CTRL1_IC_2_ADDR, REG_PLL_CLK_CTRL1_IC_2_BYTE, R1_PLL_CLK_CTRL1_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_PDN_THRMSENS_CTRL_1_IC_2_ADDR, REG_PDN_THRMSENS_CTRL_1_IC_2_BYTE, R2_PDN_THRMSENS_CTRL_1_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_PDN_CTRL2_IC_2_ADDR, REG_PDN_CTRL2_IC_2_BYTE, R3_PDN_CTRL2_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_PDN_CTRL3_IC_2_ADDR, REG_PDN_CTRL3_IC_2_BYTE, R4_PDN_CTRL3_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC_CTRL0_IC_2_ADDR, REG_DAC_CTRL0_IC_2_BYTE, R5_DAC_CTRL0_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC_CTRL1_IC_2_ADDR, REG_DAC_CTRL1_IC_2_BYTE, R6_DAC_CTRL1_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC_CTRL2_IC_2_ADDR, REG_DAC_CTRL2_IC_2_BYTE, R7_DAC_CTRL2_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC_MUTE1_IC_2_ADDR, REG_DAC_MUTE1_IC_2_BYTE, R8_DAC_MUTE1_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC_MUTE2_IC_2_ADDR, REG_DAC_MUTE2_IC_2_BYTE, R9_DAC_MUTE2_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DACMSTR_VOL_IC_2_ADDR, REG_DACMSTR_VOL_IC_2_BYTE, R10_DACMSTR_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC01_VOL_IC_2_ADDR, REG_DAC01_VOL_IC_2_BYTE, R11_DAC01_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC02_VOL_IC_2_ADDR, REG_DAC02_VOL_IC_2_BYTE, R12_DAC02_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC03_VOL_IC_2_ADDR, REG_DAC03_VOL_IC_2_BYTE, R13_DAC03_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC04_VOL_IC_2_ADDR, REG_DAC04_VOL_IC_2_BYTE, R14_DAC04_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC05_VOL_IC_2_ADDR, REG_DAC05_VOL_IC_2_BYTE, R15_DAC05_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC06_VOL_IC_2_ADDR, REG_DAC06_VOL_IC_2_BYTE, R16_DAC06_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC07_VOL_IC_2_ADDR, REG_DAC07_VOL_IC_2_BYTE, R17_DAC07_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC08_VOL_IC_2_ADDR, REG_DAC08_VOL_IC_2_BYTE, R18_DAC08_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC09_VOL_IC_2_ADDR, REG_DAC09_VOL_IC_2_BYTE, R19_DAC09_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC10_VOL_IC_2_ADDR, REG_DAC10_VOL_IC_2_BYTE, R20_DAC10_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC11_VOL_IC_2_ADDR, REG_DAC11_VOL_IC_2_BYTE, R21_DAC11_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC12_VOL_IC_2_ADDR, REG_DAC12_VOL_IC_2_BYTE, R22_DAC12_VOL_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_CM_SEL_PAD_STRGTH_IC_2_ADDR, REG_CM_SEL_PAD_STRGTH_IC_2_BYTE, R27_CM_SEL_PAD_STRGTH_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC_POWER1_IC_2_ADDR, REG_DAC_POWER1_IC_2_BYTE, R28_DAC_POWER1_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC_POWER2_IC_2_ADDR, REG_DAC_POWER2_IC_2_BYTE, R29_DAC_POWER2_IC_2_Default );
	SIGMA_WRITE_REGISTER_BLOCK( DEVICE_ADDR_IC_2, REG_DAC_POWER3_IC_2_ADDR, REG_DAC_POWER3_IC_2_BYTE, R30_DAC_POWER3_IC_2_Default );
}

#endif
